
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author breyo
 */
public class doctreg extends javax.swing.JFrame {

    /**
     * Creates new form doctreg
     */
    public doctreg() {
        initComponents();
        setSize(530,400);
        autoid();
    }
    public void autoid(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else {
                System.out.println("Failed to make connection!");
            }
             Statement stmt;
            stmt = con.createStatement();
            ResultSet rs= null;
            PreparedStatement pst = null;
            
            String q1 = ("select max(id) from doct");
             pst = con.prepareStatement(q1);
             rs=pst.executeQuery();
             //int x = stmt.executeUpdate(q1);
             //System.out.println(x);
            
            if(rs.next()){
                int id = rs.getInt(1);
                id++;
                did.setText(Integer.toString(id));
            }
            
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        did = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        ag = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        gen = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Doctor Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(129, 11, 204, 28);

        jLabel2.setText("Doctor Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 71, 78, 14);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 117, 78, 14);

        jLabel4.setText("gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 157, 78, 14);

        jLabel5.setText("age");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 199, 78, 14);

        jLabel6.setText("Contact Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 246, 78, 14);

        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(296, 71, 62, 14);

        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(296, 117, 62, 14);
        getContentPane().add(pass);
        pass.setBounds(362, 110, 103, 29);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(362, 64, 103, 28);
        getContentPane().add(did);
        did.setBounds(108, 64, 102, 28);
        getContentPane().add(name);
        name.setBounds(108, 110, 102, 29);
        getContentPane().add(ag);
        ag.setBounds(108, 192, 102, 28);
        getContentPane().add(num);
        num.setBounds(108, 238, 102, 31);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(279, 229, 90, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(387, 229, 55, 23);

        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        getContentPane().add(gen);
        gen.setBounds(108, 157, 102, 24);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\breyo\\Pictures\\Saved Pictures\\istockphoto-1003420604-1024x1024.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-240, -130, 760, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        doctinfo di = new doctinfo();
        di.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else {
                System.out.println("Failed to make connection!");
            }
            String d = "doctor";
            String id = (did.getText());
            String na = (name.getText());
            String ge = gen.getSelectedItem().toString();
            int a = Integer.parseInt(ag.getText());
            int pno = Integer.parseInt(num.getText());
            String ad = (user.getText());
           
            String text = pass.getText();

            Statement stmt;
            stmt = con.createStatement();
            String q2 = "INSERT INTO LOGIN VALUES('" + ad + "','" + text + "','" + d + "')";
            
            String q1 = "INSERT INTO DOCT VALUES('"+ id +"','" + na + "','" + ge + "','" + a + "','" + pno + "','" + ad + "','" + text + "')";
            
            int x = stmt.executeUpdate(q1);
            int y = stmt.executeUpdate(q2);
            if (x>0 && y>0) {
                JOptionPane.showMessageDialog(null, "DETAILS ADDED !");
                //setVisible(false);
                //F8 f8 = new F8();
                //f8.setVisible(true);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } catch (HeadlessException | ClassNotFoundException | IllegalAccessException | InstantiationException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctreg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ag;
    private javax.swing.JTextField did;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField num;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
