import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fredi
 */
public class F1 extends javax.swing.JFrame {

    /**
     * Creates new form F1
     */
    public F1() {
        initComponents();
        setSize(660,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        user_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jtable4 = new javax.swing.JLabel();
        user = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 100, 124, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 140, 124, 22);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 250, 110, 31);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 250, 110, 31);

        user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_idActionPerformed(evt);
            }
        });
        getContentPane().add(user_id);
        user_id.setBounds(460, 90, 130, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Login Page");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 40, 150, 33);
        getContentPane().add(password);
        password.setBounds(460, 140, 130, 30);

        jtable4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jtable4.setText("User Type");
        getContentPane().add(jtable4);
        jtable4.setBounds(280, 190, 120, 20);

        user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select user", "admin", "doctor", "receptionist" }));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(460, 190, 130, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\breyo\\Pictures\\Saved Pictures\\istockphoto-1003420604-1024x1024.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-40, 0, 770, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step3 create the statement object
   //step2 create  the connection object
    Connection con = DriverManager.getConnection(  "jdbc:oracle:thin:@localhost:1521:breyo","system","hackpassword123");
        //step3 create the statement object
        Statement stmt=con.createStatement();
        //step4 execute query
        ResultSet rs=stmt.executeQuery("select * from LOGIN");// where user_id='"+user_id.getText()+"' and password='"+password.getText()+"'");
       int temp=0;
       String usertype = user.getSelectedItem().toString();
       System.out.println(usertype);
        while(rs.next()) {
            try{
            if(rs.getString(1).equals(user_id.getText()) && rs.getString(2).equals(password.getText()) && rs.getString(3).equals(usertype))
            {     JOptionPane.showMessageDialog(null,"Login success!");
            temp=1;
            setVisible(false);
            if(usertype == "admin"){
            admin cc=new admin();
            cc.setVisible(true);}
            if(usertype == "doctor"){
                doctor cd = new doctor();
                cd.setVisible(true);
            }
            if(usertype == "receptionist"){
                recep cr = new recep();
                cr.setVisible(true);
            }
            break;}
            }catch(Exception ex){System.out.println(ex);}
//rs.getString(1)+"  "+rs.getString(2));
        }
        try{
        if(temp==0)
        {
               JOptionPane.showMessageDialog(null,"Login failed!");
        }
        }catch(Exception e){System.out.println(e);}
       // else
         //   System.out.println("Login failed");
//step5 close the connection object
   }    catch (SQLException | ClassNotFoundException ex) {  
            Logger.getLogger(F1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        //step4 execute query
     setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jtable4;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> user;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
