
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fredi
 */
public class F4 extends javax.swing.JFrame {
    
    /**
     * Creates new form F4
     */
    public F4() {
        initComponents();
        setSize(710,420);
        listfill();
        fillcombo();
    }
    private void fillcombo(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            ResultSet rs= null;
        PreparedStatement pst = null;
            
            String sql = "select distinct pid from pat";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                String id =rs.getString("pid");
                pid.addItem(id);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void listfill(){
        DefaultListModel m = new DefaultListModel();
         try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step3 create the statement object
   //step2 create  the connection object
    Connection con = DriverManager.getConnection(  "jdbc:oracle:thin:@localhost:1521:breyo","system","hackpassword123");
        //step3 create the statement object
        Statement stmt=con.createStatement();
        //step4 execute query
        ResultSet rs=stmt.executeQuery("select * from PAT");
        while(rs.next()){
            String id = rs.getString("regid");
            m.addElement(id); 
        }
        jlist2.setModel(m);
            }    catch (SQLException | ClassNotFoundException ex) {  
            Logger.getLogger(F1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        na = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        ag = new javax.swing.JTextField();
        nu = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        da = new javax.swing.JTextField();
        di = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        de = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        pid = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Patient Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 40, 214, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel2.setText("PATIENT ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 50, 78, 20);

        jlist2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlist2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jlist2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 70, 78, 240);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 90, 46, 13);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("GENDER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 120, 46, 13);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("AGE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 160, 46, 13);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel6.setText("NUMBER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 200, 46, 13);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel7.setText("ADDRESS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 240, 60, 13);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel8.setText("DATE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 280, 46, 13);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("DISEASE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 100, 70, 13);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setText("DESCRIPTION");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 160, 110, 13);
        getContentPane().add(na);
        na.setBounds(280, 82, 125, 30);
        getContentPane().add(gen);
        gen.setBounds(280, 120, 125, 30);

        ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agActionPerformed(evt);
            }
        });
        getContentPane().add(ag);
        ag.setBounds(280, 158, 125, 30);
        getContentPane().add(nu);
        nu.setBounds(280, 196, 125, 30);
        getContentPane().add(ad);
        ad.setBounds(280, 234, 125, 30);
        getContentPane().add(da);
        da.setBounds(280, 272, 125, 30);
        getContentPane().add(di);
        di.setBounds(573, 82, 118, 30);

        jScrollPane1.setViewportView(de);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(573, 116, 118, 110);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(472, 304, 90, 21);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 340, 86, 21);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 300, 80, 21);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton4.setText("MEDICINE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(530, 250, 90, 23);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel12.setText("REG ID");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 50, 60, 13);

        getContentPane().add(pid);
        pid.setBounds(570, 50, 120, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\breyo\\Pictures\\Saved Pictures\\istockphoto-1003420604-1024x1024.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-200, -130, 970, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        F5 f5 = new F5();
        f5.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Pat_info f2 = new Pat_info();
        f2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jlist2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlist2MouseClicked
        // TODO add your handling code here:
        String tmp=(String)jlist2.getSelectedValue();
         try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step3 create the statement object
   //step2 create  the connection object
    Connection con = DriverManager.getConnection(  "jdbc:oracle:thin:@localhost:1521:breyo","system","hackpassword123");
        //step3 create the statement object
        Statement stmt=con.createStatement();
        //step4 execute query
        ResultSet rs= null;
        PreparedStatement pst = null;
        String r = pid.getSelectedItem().toString();
        String sql = "SELECT * FROM PAT WHERE PID = '"+r+"' AND REGID=?";
        pst = con.prepareStatement(sql);
        pst.setString(1, tmp);
        rs=pst.executeQuery();
        if(rs.next()){
            //String ad0 = rs.getString("reg");
            //rid.setText(ad0);
            String ad1 = rs.getString("pname");
            na.setText(ad1);
            String ad2 = rs.getString("gender");
            gen.setText(ad2);
            int ad3 = rs.getInt("age");
            String st1 = Integer.toString(ad3);
            ag.setText(st1);
            int ad4 = rs.getInt("phnum");
            String st2 = Integer.toString(ad4);
            nu.setText(st2);
            String ad5 = rs.getString("addr");
            ad.setText(ad5);
            String ad6 = rs.getString("dat");
            da.setText(ad6);
            String ad7 = rs.getString("disease");
            di.setText(ad7);
            String ad8 = rs.getString("description");
            de.setText(ad8);
        }
        
        }    catch (SQLException | ClassNotFoundException ex) {  
            Logger.getLogger(F1.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }//GEN-LAST:event_jlist2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try  {
            
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            String tmp=(String)jlist2.getSelectedValue();
            //String tmp = pid.getText();
            
            java.sql.Statement st = null;
            Statement stmt = con.createStatement();
            String n = na.getText();
            String g = gen.getText();
            int a = Integer.parseInt(ag.getText());            
            int nm = Integer.parseInt(nu.getText());
            String ar = ad.getText();
            String d = da.getText();
            String ds = di.getText();
            String dp = de.getText();
            String r = pid.getSelectedItem().toString();
            
            String q1 = "UPDATE PAT SET PNAME='"+n+"',GENDER='"+g+"',AGE='"+a+"',PHNUM = '"+nm+"',ADDR='"+ar+"',DISEASE='"+ds+"',DESCRIPTION='"+dp+"' WHERE PID='"+r+"'";
            
            int x = stmt.executeUpdate(q1);
            if(x>0){
                JOptionPane.showMessageDialog(null,"DETAILS UPDATED!");
            
            }
            else
            {
                  JOptionPane.showMessageDialog(null,"INVALID!");  
                    }
            
            
            }
        catch (SQLException e)
        {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
            System.out.println(e);
        }
        catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try  {
            
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            String tmp=(String)jlist2.getSelectedValue();
           
            String r = pid.getSelectedItem().toString();
            
            java.sql.Statement st = null;
            Statement stmt = con.createStatement();
            String q1 = "DELETE FROM PAT WHERE PID='"+ r +"'";
            String q2 ="DELETE FROM MED WHERE REGID='"+ tmp +"'";
            int y = stmt.executeUpdate(q2);
            int x = stmt.executeUpdate(q1);
            
            if(x>0){
                JOptionPane.showMessageDialog(null,"DETAILS DELETED!");
            
            }
            else
            {     try{
                  JOptionPane.showMessageDialog(null,"INVALID!"); 
            }catch(Exception e){System.out.println(e);}
            }
        }
        catch (SQLException e)
        {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
        }
        catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
e.printStackTrace();}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JTextField ag;
    private javax.swing.JTextField da;
    private javax.swing.JTextPane de;
    private javax.swing.JTextField di;
    private javax.swing.JTextField gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlist2;
    private javax.swing.JTextField na;
    private javax.swing.JTextField nu;
    private javax.swing.JComboBox<String> pid;
    // End of variables declaration//GEN-END:variables
}
