
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fredi
 */
public class F7 extends javax.swing.JFrame {

    /**
     * Creates new form F7
     */
    public F7() {
        initComponents();
        setSize(638,380);
        fillcombo();
    }
    
    private void fillcombo(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            ResultSet rs= null;
        PreparedStatement pst = null;
            
            String sql = "select * from medstock";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                String id =rs.getString("mid");
                mid.addItem(id);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        qn = new javax.swing.JTextField();
        pe = new javax.swing.JTextField();
        cy = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pl = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        mid = new javax.swing.JComboBox<>();
        mi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("UPDATE MEDICINE STOCK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 319, 28);

        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 70, 70, 14);

        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 110, 70, 14);

        jLabel4.setText("QUANTITY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 150, 70, 14);

        jLabel5.setText("PRICE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 70, 14);

        jLabel6.setText("COMPANY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 230, 70, 14);

        jLabel7.setText("PLACE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 270, 70, 14);
        getContentPane().add(mn);
        mn.setBounds(141, 109, 144, 30);
        getContentPane().add(qn);
        qn.setBounds(141, 147, 144, 30);
        getContentPane().add(pe);
        pe.setBounds(141, 185, 144, 30);
        getContentPane().add(cy);
        cy.setBounds(140, 220, 144, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(391, 160, 77, 23);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 160, 81, 23);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 220, 73, 23);
        getContentPane().add(pl);
        pl.setBounds(141, 257, 144, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton4.setText("DISPLAY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(450, 100, 80, 21);

        getContentPane().add(mid);
        mid.setBounds(290, 70, 100, 30);
        getContentPane().add(mi);
        mi.setBounds(140, 70, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\breyo\\Pictures\\Saved Pictures\\istockphoto-1003420604-1024x1024.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-200, -140, 840, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        F6 f6 = new F6();
        f6.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try  {
            
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            
            String id=(mi.getText());
            String me=(mn.getText());
            String qt=(qn.getText());
            int pr=Integer.parseInt(pe.getText());
            String co=(cy.getText());
            String pc=(pl.getText());
            
            java.sql.Statement st = null;
            Statement stmt;
            stmt = con.createStatement();
           String q1 = "INSERT INTO MEDSTOCK VALUES('"+id+"','"+me+"','"+qt+"','"+pr+"','"+co+"','"+pc+"')";
            int x = stmt.executeUpdate(q1);
            if(x>0)
                JOptionPane.showMessageDialog(null,"DETAILS ADDED !");
            
            }
        catch (SQLException e)
        {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
        }
        catch (HeadlessException | ClassNotFoundException | IllegalAccessException | InstantiationException | NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try  {
            
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            
            java.sql.Statement st = null;
            Statement stmt = con.createStatement();
            String n = mid.getSelectedItem().toString();
            String g = mn.getText();
            int a = Integer.parseInt(pe.getText());            
            
            String ar = qn.getText();
            String d = cy.getText();
            String ds = pl.getText();
            
            
            String q1 = "UPDATE MEDSTOCK SET MNAME='"+g+"',QUANTITY='"+ar+"',PRICE='"+a+"',COMPANY = '"+d+"',PLACE='"+ds+"' WHERE MID='"+n+"'";
            
            int x = stmt.executeUpdate(q1);
            if(x>0){
                JOptionPane.showMessageDialog(null,"DETAILS UPDATED!");
            
            }
            else
            {
                  JOptionPane.showMessageDialog(null,"INVALID!");  
                    }
            
            
            }
        catch (SQLException e)
        {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
            System.out.println(e);
        }
        catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try  {
            
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            java.sql.Statement st = null;
            Statement stmt;
            stmt = con.createStatement();
            String md = (mid.getSelectedItem().toString());
            
            
            
           ResultSet rs= null;
        PreparedStatement pst = null;
        
        String sql = "SELECT * FROM MEDSTOCK WHERE MID = '"+md+"'";
        pst = con.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
            String m = rs.getString("mname");
            mn.setText(m);
            String q = rs.getString("quantity");
            qn.setText(q);
            int p= rs.getInt("price");
            pe.setText(Integer.toString(p));
            String c = rs.getString("company");
            cy.setText(c);
            String pc = rs.getString("place");
            pl.setText(pc);
            
        }
        }catch (SQLException e)
        {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
            System.out.println(e);
        }
        catch (HeadlessException | ClassNotFoundException | IllegalAccessException | InstantiationException | NumberFormatException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mi;
    private javax.swing.JComboBox<String> mid;
    private javax.swing.JTextField mn;
    private javax.swing.JTextField pe;
    private javax.swing.JTextField pl;
    private javax.swing.JTextField qn;
    // End of variables declaration//GEN-END:variables
}
