
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fredi
 */
public class F8 extends javax.swing.JFrame {

    /**
     * Creates new form F8
     */
    public F8() {
        initComponents();
        setSize(650,350);
        showdate();
        fillcombo1();
        fillcombo2();
    }
        void showdate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-YYYY");
        da.setText(s.format(d));
    }
        
        private void fillcombo1(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            ResultSet rs= null;
        PreparedStatement pst = null;
            
            String sql = "select distinct regid from pat";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                String id =rs.getString("regid");
                rid.addItem(id);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
        private void fillcombo2(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            ResultSet rs= null;
        PreparedStatement pst = null;
            
            String sql = "select distinct mid from medstock";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                String id =rs.getString("mid");
                mid.addItem(id);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        qn = new javax.swing.JTextField();
        pe = new javax.swing.JTextField();
        da = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        rid = new javax.swing.JComboBox<>();
        mid = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("PATIENT MEDICINE REGISTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(147, 11, 354, 28);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("REG ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 63, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("M ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 100, 63, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("M NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 140, 63, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("QUANTITY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 180, 63, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("PRICE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 220, 63, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("DATE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 250, 63, 14);
        getContentPane().add(mn);
        mn.setBounds(197, 129, 121, 30);
        getContentPane().add(qn);
        qn.setBounds(197, 167, 121, 30);
        getContentPane().add(pe);
        pe.setBounds(197, 206, 121, 30);

        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });
        getContentPane().add(da);
        da.setBounds(200, 250, 121, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(415, 177, 75, 21);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(532, 177, 71, 21);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton3.setText("DISPLAY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 120, 90, 21);

        getContentPane().add(rid);
        rid.setBounds(200, 50, 120, 30);

        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        getContentPane().add(mid);
        mid.setBounds(200, 90, 120, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\breyo\\Pictures\\Saved Pictures\\istockphoto-1003420604-1024x1024.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-200, -150, 840, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try  {
            
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            java.sql.Statement st = null;
            Statement stmt;
            stmt = con.createStatement();
            
            
            
            
            String id=(rid.getSelectedItem().toString());
            String md = (mid.getSelectedItem().toString());
            String me=(mn.getText());
            String qt=(qn.getText());
            int pr=Integer.parseInt(pe.getText());
            String dt=(da.getText());
            
            
           String q1 = "INSERT INTO MED VALUES('"+md+"','"+id+"','"+me+"','"+qt+"','"+pr+"','"+dt+"')";
            int x = stmt.executeUpdate(q1);
            if(x>0)
                JOptionPane.showMessageDialog(null,"DETAILS ADDED !");
            
            }
        catch (SQLException e)
        {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
        }
        catch (HeadlessException | ClassNotFoundException | IllegalAccessException | InstantiationException | NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        F3 f3 = new F3();
        f3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_daActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try  {
            
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else 
            {
                System.out.println("Failed to make connection!");
            }
            java.sql.Statement st = null;
            Statement stmt;
            stmt = con.createStatement();
            String md = (mid.getSelectedItem().toString());
            
            
            
           ResultSet rs= null;
        PreparedStatement pst = null;
        
        String sql = "SELECT * FROM MEDSTOCK WHERE MID = '"+md+"'";
        pst = con.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
            String m = rs.getString("mname");
            mn.setText(m);
            String q = rs.getString("quantity");
            qn.setText(q);
            int p= rs.getInt("price");
            pe.setText(Integer.toString(p));
            
        }
        }catch (SQLException e)
        {
            System.err.format("SQL State: %s\n%s", e.getSQLState(), e.getMessage());
        }
        catch (HeadlessException | ClassNotFoundException | IllegalAccessException | InstantiationException | NumberFormatException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField da;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> mid;
    private javax.swing.JTextField mn;
    private javax.swing.JTextField pe;
    private javax.swing.JTextField qn;
    private javax.swing.JComboBox<String> rid;
    // End of variables declaration//GEN-END:variables
}
