
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author breyo
 */
public class rereg extends javax.swing.JFrame {

    /**
     * Creates new form rereg
     */
    public rereg() {
        initComponents();
        setSize(560,370);
        autoid();
    }
    public void autoid(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else {
                System.out.println("Failed to make connection!");
            }
             Statement stmt;
            stmt = con.createStatement();
            ResultSet rs= null;
            PreparedStatement pst = null;
            
            String q1 = ("select max(id) from recep");
             pst = con.prepareStatement(q1);
             rs=pst.executeQuery();
             //int x = stmt.executeUpdate(q1);
             //System.out.println(x);
            
            if(rs.next()){
                int id = rs.getInt(1);
                id++;
                rid.setText(Integer.toString(id));
            }
            
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        na = new javax.swing.JTextField();
        ag = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        gen = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Receptionist Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(146, 21, 196, 22);

        jLabel2.setText("id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(57, 87, 40, 14);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 130, 50, 14);

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(62, 186, 60, 14);

        jLabel5.setText("Age");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(78, 239, 40, 14);

        jLabel6.setText("Contact Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(19, 286, 100, 14);
        getContentPane().add(rid);
        rid.setBounds(126, 74, 102, 30);
        getContentPane().add(na);
        na.setBounds(126, 122, 102, 30);
        getContentPane().add(ag);
        ag.setBounds(126, 226, 102, 30);
        getContentPane().add(num);
        num.setBounds(126, 273, 102, 30);

        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        getContentPane().add(gen);
        gen.setBounds(126, 173, 102, 30);

        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(281, 87, 70, 14);

        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(281, 135, 70, 14);
        getContentPane().add(user);
        user.setBounds(360, 74, 130, 30);
        getContentPane().add(pass);
        pass.setBounds(360, 122, 130, 30);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 260, 100, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 260, 90, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\breyo\\Pictures\\Saved Pictures\\istockphoto-1003420604-1024x1024.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-6, -6, 550, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection con = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:breyo", "system", "hackpassword123");
            if (con != null) {
                System.out.println("Connected to the database!");
            } else {
                System.out.println("Failed to make connection!");
            }
            String d = "receptionist";
            String id = (rid.getText());
            String nam = (na.getText());
            String ge = gen.getSelectedItem().toString();
            int a = Integer.parseInt(ag.getText());
            int pno = Integer.parseInt(num.getText());
            String ad = (user.getText());
           
            String text = pass.getText();
            //java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy");
            //java.time.LocalDate textFieldAsDate = java.time.LocalDate.parse(text, formatter);
            //java.sql.Date dat = java.sql.Date.valueOf(textFieldAsDate);
            //String dee = (disease.getText());
            //String desn = (des.getText());
            //String rd = (rid.getText());
            
            
            Statement stmt;
            stmt = con.createStatement();
            String q2 = "INSERT INTO LOGIN VALUES('" + ad + "','" + text + "','" + d + "')";
            
            String q1 = "INSERT INTO RECEP VALUES('"+ id +"','" + nam + "','" + ge + "','" + a + "','" + pno + "','" + ad + "','" + text + "')";
            
            int x = stmt.executeUpdate(q1);
            int y = stmt.executeUpdate(q2);
            if (x>0 && y>0) {
                JOptionPane.showMessageDialog(null, "DETAILS ADDED !");
                //setVisible(false);
                //F8 f8 = new F8();
                //f8.setVisible(true);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        } catch (HeadlessException | ClassNotFoundException | IllegalAccessException | InstantiationException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ERROR", "WARNING", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rereg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rereg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rereg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rereg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rereg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ag;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField na;
    private javax.swing.JTextField num;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField rid;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
